### ISSUE TITLE
LoggerService Port

### ISSUE THREAD

**Issue by ChristianKniep** [josefbacik/kernelscope#4]
In your README you start the loggerservice like that, depending on whether one uses MySQL or sqlite.

```
python KernelscopeService.py --mysql localhost --dbuser user --dbpassword password --dbname kernelscope 8080
python KernelscopeLoggerService.py --sqlite kernelscope.db 8081
```

But should they use the same script and the same port?

**Comment by ChristianKniep** [comment]
Subsequent: I have to start the offcputime process like this (different port):

```
$ python offcputime.py --logger 'http://localhost:8081' --threshold 5000
```

**Comment by josefbacik** [comment]
So the KernelscopeService is the thing that the web browser connects to in order to get the pretty pictures, the KernelscopeLoggerService is what the machines you are profiling connect to.  So for sqllite you do something like this

    $ python KernelscopeLoggerService.py --sqlite kernelscope.db 8081
    $ python KernelscopeService.py --sqlite kernelscope.db 8080

Then you run

    $ python offcputime.py --logger 'http://localhost:8081' --threshold 5000

**Comment by josefbacik** [comment]
Oh I see what you are saying, oops I'll fix that up.
